import './styles/main.styl'
// import './javascript/app.js'
// import './javascript/gl1.js'
// import './javascript/gl2.js'
// import './javascript/gl3.js'
// import './javascript/gl4.js'
// import './javascript/gl5.js'
// import './javascript/gl6.js'
import './javascript/gl7.js'