import './styles/main.styl'
// import './javascript/app.js'
// import './javascript/demo/gl1.js'
// import './javascript/demo/gl2.js'
// import './javascript/demo/gl3.js'
// import './javascript/demo/gl4.js'
// import './javascript/demo/gl5.js'
// import './javascript/demo/gl6.js'
// import './javascript/demo/gl7.js'
// import './javascript/demo/gl8.js'
import './javascript/equalizer2.js'